version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: data/web_container/Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      - "postgres"
    restart: always
    read_only: true
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    mem_limit: "512m"
    mem_reservation: "128m"
    cpus: "1.75"
    volumes:
      - ./data/hsm_tokens:/var/lib/softhsm/tokens
    tmpfs:
      - /dev/shm:ro,noexec,nosuid,nodev
    environment:
      - PKCS11_TOKEN=my_test_token_1
      - PKCS11_PIN=1234
      - PKCS11_MODULE=/usr/lib/softhsm/libsofthsm2.so

  postgres:
    image: postgres:15.0-bullseye@sha256:e21150abf83d89aca1b61c8ccc182cc8164da2571a0d8ee0babce8790bed46ab
    restart: always
    # read_only: true
    # cap_drop: [ALL]
    # security_opt:
    #   - no-new-privileges:true
    mem_limit: "1g"
    mem_reservation: "128m"
    cpus: "1.75"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
    tmpfs:
      - /dev/shm:ro,noexec,nosuid,nodev
    environment:
      - POSTGRES_DB=pkcs11_testdb1
      - POSTGRES_USER=pkcs11_testuser1
      - POSTGRES_PASSWORD=DBUserPassword
