version: "3.3"
# Require docker-compose version 1.29
# version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: data/web_container/Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      - "postgres"
    restart: always
    read_only: true
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    # Require docker-compose version 1.29 and version: "3.3" in this file at the top
    # mem_limit: "512m"
    # mem_reservation: "128m"
    # cpus: "1.75"
    volumes:
      - ./data/hsm_tokens:/var/lib/softhsm/tokens
    tmpfs:
      - /dev/shm:ro,noexec,nosuid,nodev
    environment:
      - CA_URL=${CA_URL}
      - PKCS11_SIGN_API_TOKEN=${PKCS11_SIGN_API_TOKEN}
      - PKCS11_TOKEN=${PKCS11_TOKEN}
      - PKCS11_PIN=${PKCS11_PIN}
      - PKCS11_MODULE=${PKCS11_MODULE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
  postgres:
    # build:
    # context: .
    # dockerfile: data/postgres_container/Dockerfile
    image: postgres:15.2-bullseye@sha256:cf629afce2e1faebb80b5dc0d8c0981cf32981012b782de4d6dc2bd98aaeb010
    restart: always
    # read_only: true
    # cap_drop: [ALL]
    # security_opt:
    #   - no-new-privileges:true
    # Require docker-compose version 1.299 and version: "3.3" in this file at the top
    # mem_limit: "1g"
    # mem_reservation: "128m"
    # cpus: "1.75"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
    tmpfs:
      - /dev/shm:ro,noexec,nosuid,nodev
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  test1:
    build:
      context: .
      dockerfile: data/test_container/Dockerfile
    depends_on:
      - "web"
    restart: "no"
    # read_only: true
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    # Require docker-compose version 1.29 and version: "3.3" in this file at the top
    # mem_limit: "256m"
    # mem_reservation: "128m"
    # cpus: "1.0"
    tmpfs:
      - /dev/shm:ro,noexec,nosuid,nodev
    environment:
      - CA_URL=${CA_URL}
      - PKCS11_SIGN_API_TOKEN=${PKCS11_SIGN_API_TOKEN}
    entrypoint: ['true']
