description = "Python async library for signing x509 using keys in an pkcs11 device such as a HSM"
version = "0.1.3"

[build-system]
requires = [
    "flit_core >=2.0",
]

[tool.flit.metadata]
module = "pkcs11_ca_service"

description-file = "README.md"
requires-python = ">=3.7"

keywords = "x509,pkcs11,CA,HSM"
license = "MIT"
author = "Victor Näslund"
author-email = "victor@sunet.se"
# home-page = "https://github.com/SUNET/python_x509_pkcs11"

requires = [
    "asn1crypto>=1.4.0",
    "pyjwt>=1.7.1"
]
