name: python_pkcs11_ca-debian

on: [push]

jobs:
  container-test-job:

    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install git python3-dev python3-pip docker.io docker-compose sudo mypy black pylint flit -y
          useradd python_pkcs11_ca -m
          usermod -a -G sudo python_pkcs11_ca
          usermod -a -G docker python_pkcs11_ca
          sudo -u python_pkcs11_ca bash -c 'export PATH="$PATH:$HOME/.local/bin" && \
          id && \
          cd && \
          git clone https://github.com/SUNET/pkcs11_ca.git && \
          cd pkcs11_ca && \
          bash dev-run.sh'
