name: python_pkcs11_ca-debian

on: [push]

jobs:
  container-test-job:

    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          id
          sudo apt-get update
          sudo apt-get install git python3-dev python3-pip docker.io docker-compose sudo flit curl -y
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu kinetic stable"
          sudo apt-get update
          sudo apt install docker-ce docker-ce-cli containerd.io -y
          sudo useradd python_pkcs11_ca -m
          sudo usermod -a -G sudo python_pkcs11_ca
          sudo usermod -a -G docker python_pkcs11_ca
          sudo systemctl restart docker
          # sudo echo 'python_pkcs11_ca ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
          sudo -u python_pkcs11_ca bash -c 'export PATH="$PATH:$HOME/.local/bin" && \
          export CA_URL=https://web:8005 && \
          export CA_DNS_NAME=web && \
          export PKCS11_TOKEN=my_test_token_1 && \
          export PKCS11_PIN=1234 && \
          export PKCS11_MODULE=/usr/lib/softhsm/libsofthsm2.so && \
          export POSTGRES_HOST=postgres && \
          export POSTGRES_USER=pkcs11_testuser1 && \
          export POSTGRES_PASSWORD=DBUserPassword && \
          export POSTGRES_PORT=5432 && \
          export POSTGRES_DATABASE=pkcs11_testdb1 && \
          export POSTGRES_TIMEOUT=5 && \
          id && \
          cd && \
          git clone https://github.com/SUNET/pkcs11_ca.git && \
          cd pkcs11_ca && \
          python3 -m pip install -r requirements.txt && \
          python3 -m pip install types-requests mypy black pylint && \
          bash dev-run.sh'
